### ISSUE TITLE
Add Machine Types

### ISSUE THREAD

**Issue by nZeloT** [nZeloT/PFHSim#21]
Add machines types to support multiple machines which can produce different wall types

**Comment by XLexxaX** [comment]
Do the different type of machines have an impact on which type of walls a machine can produce? Or do the MachineTypes only affect the output (besides price, cost, ...) ?

**Comment by nZeloT** [comment]
The machine type defines which wall types can be produced by the according machine

**Comment by XLexxaX** [comment]
ok, implementation adjusted as per description.
