### ISSUE TITLE
Production house / Machine Type enhancement

### ISSUE THREAD

**Issue by ghost** [nZeloT/PFHSim#22]
Is anobody on this already? otherwise I can do that:

Tasks Production House:
- add attribute base costs: 500
- add possibility to buy machines
- getters & setters

Machine Type enhancement as defined in calculations

**Comment by XLexxaX** [comment]
No, I'm not... you can do it if you want ;)

**Comment by nZeloT** [comment]
Sure go ahead. Employee mgmt is not needed im that one? Is it? Should be handeld through machine entirely.

**Comment by nZeloT** [comment]
@flodesflo this is finished. Isn't it?
