### ISSUE TITLE
Simulation Step: Group of buyers "Cheap Buyer"

### ISSUE THREAD

**Issue by XLexxaX** [nZeloT/PFHSim#26]
Between the end of one game-period and the beginning of the next one, a market simulation should simulate different group of buyers which choose offers from enterprises' catalogues to trigger the construction of a PFHouse.

**Comment by XLexxaX** [comment]
Flo and I have started implementation.

**Comment by XLexxaX** [comment]
I will structure the implementation in terms of object-oriented programming by adding an interface.
Likewise I will cockle (eng. zusammenziehen) the two variables "enterprises" and "offers" within another tupel.
The inner-class-tupels will be outsourced from "Simulation"-class.

**Comment by XLexxaX** [comment]
@nZeloT Please take a look at the new construction, it is way better; now satisfied? ;)

**Comment by nZeloT** [comment]
@XLexxaX this is fine now

**Comment by XLexxaX** [comment]
TO DO: 
- as discussed, the Buyer-classes will only get offers from the client; enterprise in hashmap = numbers
