### ISSUE TITLE
Quality concept

### ISSUE THREAD

**Issue by XLexxaX** [nZeloT/PFHSim#39]
The quality values are not used currently. With a first concept, this circumstance should change.

**Comment by XLexxaX** [comment]
@nZeloT @flodesflo @wolfmarcel @carmabell 
Could you please review the concept?
Link:
https://github.com/nZeloT/PFHSim/blob/master/res/QualityConcept.md

**Comment by nZeloT** [comment]
@XLexxaX added some comments ;)

**Comment by XLexxaX** [comment]
@nZeloT Added response ;)
