### ISSUE TITLE
UI for Production

### ISSUE THREAD

**Issue by carmabell** [nZeloT/PFHSim#45]
please also add an Label which wall is currently in production. 
Apart from that you can realize ui from the mock-up

For help with JAVA FX see our results from yesterday or ask us.

**Comment by carmabell** [comment]
@wolfmarcel : try to integrate a scroll bar because of the unlimited number of machines, which a player could buy

**Comment by nZeloT** [comment]
@wolfmarcel @carmabell please don't just place a scrollbar or so; use a list view and the design a second FXML file which is one entry in this list; we`ll then do a bit of coding to get this dynamically generated like I did it for HR

**Comment by wolfmarcel** [comment]
Allright:)

Von meinem iPhone gesendet
