### ISSUE TITLE
ui: warehouse

### ISSUE THREAD

**Issue by nZeloT** [nZeloT/PFHSim#47]
please also take a look on the warehouse screen; some labels shrink until they ate not readable any more; additionally the numbers are not aligned properly into their distinctive rows.

**Comment by nZeloT** [comment]
additionally even when no upgrade is in process and the update method is beeing executed because a new round is about to start the progress of extension is shown as increased.

**Comment by nZeloT** [comment]
what about having the icons from procurement also on this screen?

**Comment by XLexxaX** [comment]
@nZeloT I have pushed the latest change. Is that now what you have imagined?

**Comment by carmabell** [comment]
shrinked labels - done
to be continued

**Comment by carmabell** [comment]
progress bar problem - think I fixed it, need to be tested
