### ISSUE TITLE
ui: offer catalog

### ISSUE THREAD

**Issue by nZeloT** [nZeloT/PFHSim#48]
the offer ui is not really responsive in any way ;) if you could do some improvement to that maybe.

**Comment by nZeloT** [comment]
maybe have the arragement you made to display the settings for one offer aligned below each other in one bis VBox which is wrapped in a scroll area or so; it would then stop looking a bit clunky :)
also why do we need a load offer details button?

**Comment by XLexxaX** [comment]
about 1) I will continue with making my UI more responsive as soon as I can run the client. But be aware of possibly not having all figures directly shown on first view.
about 2) I guess you would prefer a mouseEventListener (or whatever it is called) instead of a load offer button...

**Comment by nZeloT** [comment]
@XLexxaX did you get it running?
for point 2 I´d suggest adding a change listener to the selectedItemProperty of the selection model from the listview. With something like that list.getSelectionModel().selectedItemProperty().addListener(...)

**Comment by nZeloT** [comment]
@XLexxaX when talking about the offer screen then yes. this is very nice now :) thank you
