### ISSUE TITLE
Shitstorm on you Carmen!

### ISSUE THREAD

**Issue by XLexxaX** [nZeloT/PFHSim#50]
If the player does not push ENTER in the WANTED-NUMBER field after typing in a number, his input is not regarded when buying the respective resources.

**Comment by carmabell** [comment]
@XLexxaX @nZeloT  i noticed the problem, but did not find the right method for this. I looked at Alex UI's but he did it in the same way...

**Comment by XLexxaX** [comment]
I admit, my solution is not the nicest one, but with the latest commit, all values on my screen are update in realtime --> meaning when the player types in a number, other numbers are updated.
