### ISSUE TITLE
Update function does not work

### ISSUE THREAD

**Issue by XLexxaX** [nZeloT/PFHSim#52]
The update() - method in OfferOverviewController-class is not called.

**Comment by nZeloT** [comment]
@XLexxaX please specify more concrete when it is not called?
It is only supposed to be called after you pressed the next round button and the calculation is finished;
Additionally with the next commit of me it is also called every time the user enters the respective UI

**Comment by XLexxaX** [comment]
@nZeloT I have not tested the update()-method-behaviour when pressing the next round button. 
I observed it does not work when entering the Offer-UI.
